apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: metalfactory
 namespace: default
 labels:
  prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "80"

spec: 
 replicas: 1 
 selector: 
  matchLabels: 
    app: metalfactory
 template: 
  metadata: 
    labels: 
      app: metalfactory
      prometheus.io/scrape: "true"
  prometheus.io/path: "/metrics"
  prometheus.io/port: "80"
      
  spec: 
    containers: 
      - name: metalfactory
        image: ghcr.io/droeder/metalfactory:v.0.0.1
        ports: 
          - name: http-port 
            containerPort: 5000

