apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: metalfactory
 namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec: 
 replicas: 1 
 selector: 
  matchLabels: 
    app: metalfactory
 template: 
  metadata:
    annotations: 
      prometheus.io/scrape: "true"
    labels: 
      app: metalfactory
  spec: 
    containers: 
      - name: metalfactory
        image: ghcr.io/droeder/metalfactory:v.0.0.1
        ports: 
          - name: http-port 
            containerPort: 5000

