apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: metalfactory
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    argocd.argoproj.io/sync-wave: "20"
spec:
  rules:
  - host: metalfactory.172.18.0.200.nip.io
  # - host: metalfactory.ingress.local
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: metalfactory
            port:
              number: 80
