apiVersion: v1 
kind: Service 
metadata: 
 name: metalfactory
 namespace: {{ .Values.namespace }}
spec: 
  selector: 
    app: metalfactory
  ports: 
    - name: app 
      port: 80
      targetPort: 5000