apiVersion: apps/v1 
kind: Deployment 
metadata: 
 name: metalclient
 namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec: 
 replicas: 1 
 selector: 
  matchLabels: 
    app: metalclient
 template: 
  metadata:
    # annotations: 
    #   prometheus.io/scrape: "true"
    labels: 
      app: metalclient
      
  spec: 
    containers: 
      - name: metalclient
        image: ghcr.io/droeder/metalclient:v0.0.2

