apiVersion: v1 
kind: Service 
metadata: 
 name: metalclient
 namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec: 
  selector: 
    app: metalclient
  ports: 
    - name: app 
      port: 80
      targetPort: 5000