apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root # name of the Argo CD application
  namespace: keycloak-operator
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/keycloak/keycloak-operator
    targetRevision: HEAD
    path: deploy/crds/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: operators
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
