apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: keycloak
    repoURL: https://github.com/bitnami/charts/tree/master/bitnami/keycloak
    targetRevision: 7.1.12
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
