apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root # name of the Argo CD application
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/droeder/argocd-root
    path: apps/
    targetRevision: HEAD
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
