apiVersion: v1
kind: Namespace
metadata:
  name: root

---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root # name of the Argo CD application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/droeder/argocd-root
    targetRevision: HEAD
    path: apps/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: root
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
