apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
spec:
  destination:
    name: ''
    namespace: default
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://strimzi.io/charts/'
    targetRevision: 0.29.0
    chart: strimzi-kafka-operator
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true