apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: strimzi
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  source:
    chart: strimzi-kafka-operator
    path: ""
    repoURL: "https://strimzi.io/charts/"
    targetRevision: 0.29.0
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
