apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-root # name of the Argo CD application
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/droeder/argocd-root
    targetRevision: HEAD
    # path: echo-server
    # directory:
    #   recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd-root # namespace we created
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
